## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Bro's Word | Слово Пацана - in English"
copyright = "{year}"
theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
baseURL = "https://evekeen.github.io/chush.pro/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------


[Params]
description = "Слово Пацана in Engllish"
logo = "images/bfc-logo.jpg"
favicon = true
title="Bro's Word"
author="Alexander Ivkin"
images = ["images/bfc-logo.jpg"]

[Params.social]
tiktok = "https://www.tiktok.com/@chushpan594"